apiVersion: v1
kind: Secret
metadata:
  name: ecr-refresh-aws-credentials
  namespace: example
data:
  AWSAccessKeyId: CHANGEME
  AWSSecretAccessKey: CHANGEME
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: example
  name: ecr-refresh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: example
  name: ecr-refresh
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["ecr-eu-west-1"]  # FIXME adapt to your region
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-refresh
  namespace: example
subjects:
- kind: ServiceAccount
  name: ecr-refresh
  namespace: example
roleRef:
  kind: Role
  name: ecr-refresh
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: example
  name: ecr-refresh
spec:
  template:
    spec:
      containers:
      - name: refresher
        image: abeutot/ecr_k8s_refresh:latest
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: ecr-refresh-aws-credentials
                key: AWSAccessKeyId
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ecr-refresh-aws-credentials
                key: AWSSecretAccessKey
          - name: AWS_DEFAULT_REGION
            value: "CHANGEME"
      restartPolicy: Never
      serviceAccountName: ecr-refresh
  backoffLimit: 4
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-refresh
  namespace: example
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: refresher
            image: abeutot/ecr_k8s_refresh:latest
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: ecr-refresh-aws-credentials
                    key: AWSAccessKeyId
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: ecr-refresh-aws-credentials
                    key: AWSSecretAccessKey
              - name: AWS_DEFAULT_REGION
                value: "CHANGEME"
          serviceAccountName: ecr-refresh
          restartPolicy: OnFailure
