#!/bin/sh

set -e

REGION="$AWS_DEFAULT_REGION"

PASSWORD="$(aws ecr get-login-password --region $REGION)"

REGISTRY="$(aws ecr describe-repositories --output json --region $REGION)"
REGISTRY="$(echo "$REGISTRY" | jq -r '.repositories[0].repositoryUri|split("/")[0]')"


for n in ${K8S_NAMESPACES}; do
    kubectl create secret docker-registry "ecr-$REGION" \
        --docker-username=AWS \
        --docker-password="$PASSWORD" \
        --docker-server="$REGISTRY" \
        -n "$n" \
        --dry-run=client -o yaml --save-config | kubectl apply -f -
done
